name: Azure Cart Deploy Workflow

on:
  push:
    branches: [main]

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --legacy-peer-deps
      # - run: |
      #    ng build --prod
      - uses: amondnet/vercel-action@v25 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional 
          vercel-args: '--prod' # Optional
          vercel-org-id: ${{ secrets.ORG_ID }}  # Required
          vercel-project-id: ${{ secrets.PROJECT_ID }} # Required 
          working-directory: frontend
